version: "3.9"

services:
  gallegos:
    image: ghcr.io/miguesaint/gallegos:1.0.5
    deploy:
      replicas: 1
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.gallegos.entrypoints=http"
        - "traefik.http.routers.gallegos.rule=Host(`gallegos.byronrm.com`)"
        - "traefik.http.middlewares.gallegos-https-redirect.redirectscheme.scheme=https"
        - "traefik.http.routers.gallegos.middlewares=gallegos-https-redirect"
        - "traefik.http.routers.gallegos-secure.entrypoints=https"
        - "traefik.http.routers.gallegos-secure.rule=Host(`gallegos.byronrm.com`)"
        - "traefik.http.routers.gallegos-secure.tls=true"
        - "traefik.http.routers.gallegos-secure.tls.certresolver=http"
        - "traefik.http.routers.gallegos-secure.service=gallegos"
        - "traefik.http.services.gallegos.loadbalancer.server.port=80"
        - "traefik.docker.network=traefik-public"
    networks:
      - traefik-public

networks:
  traefik-public:
    external: true
